import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../public/app.css',import.meta.url),'utf8');
test('market workflow is split into three menus',()=>{assert.match(html,/data-market-view="prediction"/);assert.match(html,/data-market-view="result"/);assert.match(html,/data-market-view="calculate"/)});
test('prize inputs are generated dynamically',()=>{assert.match(js,/predictionPrizeCount/);assert.match(js,/resultPrizeCount/);assert.match(js,/numberInputs/)});
test('nomor keluar renders last result',()=>{assert.match(html,/lastMarketResult/);assert.match(js,/renderLastResult/)});
test('mobile market controls are touch friendly',()=>{assert.match(css,/market-subtabs/);assert.match(css,/min-height:54px/)});
